"""Country-name → ISO 3166-1 alpha-2 code map.

Shodan's ``country:`` filter only accepts 2-letter ISO codes; a full name like
"Germany" or an alias like "USA"/"UK" matches zero hosts. The LLM occasionally
emits a name anyway, so :func:`resolve` lets the sanitizer rewrite the name to
its code instead of dropping the filter outright.

Keys are lowercased. We include the common English short name plus the aliases
people (and models) actually type — "usa", "uk", "uae", "south korea", "russia",
"czechia", etc. Lookups go through :func:`resolve`, which normalises the input
(case, surrounding whitespace, internal whitespace, a leading "the").
"""

from __future__ import annotations

import re
import unicodedata

# Common short name → alpha-2. Ordered roughly alphabetically by code for sanity.
NAME_TO_CODE: dict[str, str] = {
    "andorra": "AD",
    "united arab emirates": "AE",
    "afghanistan": "AF",
    "antigua and barbuda": "AG",
    "anguilla": "AI",
    "albania": "AL",
    "armenia": "AM",
    "angola": "AO",
    "antarctica": "AQ",
    "argentina": "AR",
    "american samoa": "AS",
    "austria": "AT",
    "australia": "AU",
    "aruba": "AW",
    "aland islands": "AX",
    "azerbaijan": "AZ",
    "bosnia and herzegovina": "BA",
    "barbados": "BB",
    "bangladesh": "BD",
    "belgium": "BE",
    "burkina faso": "BF",
    "bulgaria": "BG",
    "bahrain": "BH",
    "burundi": "BI",
    "benin": "BJ",
    "saint barthelemy": "BL",
    "bermuda": "BM",
    "brunei": "BN",
    "brunei darussalam": "BN",
    "bolivia": "BO",
    "bonaire": "BQ",
    "brazil": "BR",
    "bahamas": "BS",
    "bhutan": "BT",
    "bouvet island": "BV",
    "botswana": "BW",
    "belarus": "BY",
    "belize": "BZ",
    "canada": "CA",
    "cocos islands": "CC",
    "keeling islands": "CC",
    "democratic republic of the congo": "CD",
    "dr congo": "CD",
    "congo-kinshasa": "CD",
    "central african republic": "CF",
    "republic of the congo": "CG",
    "congo": "CG",
    "congo-brazzaville": "CG",
    "switzerland": "CH",
    "ivory coast": "CI",
    "cote d'ivoire": "CI",
    "cook islands": "CK",
    "chile": "CL",
    "cameroon": "CM",
    "china": "CN",
    "colombia": "CO",
    "costa rica": "CR",
    "cuba": "CU",
    "cape verde": "CV",
    "cabo verde": "CV",
    "curacao": "CW",
    "christmas island": "CX",
    "cyprus": "CY",
    "czechia": "CZ",
    "czech republic": "CZ",
    "germany": "DE",
    "djibouti": "DJ",
    "denmark": "DK",
    "dominica": "DM",
    "dominican republic": "DO",
    "algeria": "DZ",
    "ecuador": "EC",
    "estonia": "EE",
    "egypt": "EG",
    "western sahara": "EH",
    "eritrea": "ER",
    "spain": "ES",
    "ethiopia": "ET",
    "finland": "FI",
    "fiji": "FJ",
    "falkland islands": "FK",
    "micronesia": "FM",
    "faroe islands": "FO",
    "france": "FR",
    "gabon": "GA",
    "united kingdom": "GB",
    "great britain": "GB",
    "britain": "GB",
    "england": "GB",
    "scotland": "GB",
    "wales": "GB",
    "northern ireland": "GB",
    "grenada": "GD",
    "georgia": "GE",
    "french guiana": "GF",
    "guernsey": "GG",
    "ghana": "GH",
    "gibraltar": "GI",
    "greenland": "GL",
    "gambia": "GM",
    "guinea": "GN",
    "guadeloupe": "GP",
    "equatorial guinea": "GQ",
    "greece": "GR",
    "south georgia and the south sandwich islands": "GS",
    "guatemala": "GT",
    "guam": "GU",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "hong kong": "HK",
    "heard island and mcdonald islands": "HM",
    "honduras": "HN",
    "croatia": "HR",
    "haiti": "HT",
    "hungary": "HU",
    "indonesia": "ID",
    "ireland": "IE",
    "israel": "IL",
    "isle of man": "IM",
    "india": "IN",
    "british indian ocean territory": "IO",
    "iraq": "IQ",
    "iran": "IR",
    "iceland": "IS",
    "italy": "IT",
    "jersey": "JE",
    "jamaica": "JM",
    "jordan": "JO",
    "japan": "JP",
    "kenya": "KE",
    "kyrgyzstan": "KG",
    "cambodia": "KH",
    "kiribati": "KI",
    "comoros": "KM",
    "saint kitts and nevis": "KN",
    "north korea": "KP",
    "south korea": "KR",
    "korea": "KR",
    "kuwait": "KW",
    "cayman islands": "KY",
    "kazakhstan": "KZ",
    "laos": "LA",
    "lebanon": "LB",
    "saint lucia": "LC",
    "liechtenstein": "LI",
    "sri lanka": "LK",
    "liberia": "LR",
    "lesotho": "LS",
    "lithuania": "LT",
    "luxembourg": "LU",
    "latvia": "LV",
    "libya": "LY",
    "morocco": "MA",
    "monaco": "MC",
    "moldova": "MD",
    "montenegro": "ME",
    "saint martin": "MF",
    "madagascar": "MG",
    "marshall islands": "MH",
    "north macedonia": "MK",
    "macedonia": "MK",
    "mali": "ML",
    "myanmar": "MM",
    "burma": "MM",
    "mongolia": "MN",
    "macau": "MO",
    "macao": "MO",
    "northern mariana islands": "MP",
    "martinique": "MQ",
    "mauritania": "MR",
    "montserrat": "MS",
    "malta": "MT",
    "mauritius": "MU",
    "maldives": "MV",
    "malawi": "MW",
    "mexico": "MX",
    "malaysia": "MY",
    "mozambique": "MZ",
    "namibia": "NA",
    "new caledonia": "NC",
    "niger": "NE",
    "norfolk island": "NF",
    "nigeria": "NG",
    "nicaragua": "NI",
    "netherlands": "NL",
    "holland": "NL",
    "norway": "NO",
    "nepal": "NP",
    "nauru": "NR",
    "niue": "NU",
    "new zealand": "NZ",
    "oman": "OM",
    "panama": "PA",
    "peru": "PE",
    "french polynesia": "PF",
    "papua new guinea": "PG",
    "philippines": "PH",
    "pakistan": "PK",
    "poland": "PL",
    "saint pierre and miquelon": "PM",
    "pitcairn": "PN",
    "puerto rico": "PR",
    "palestine": "PS",
    "portugal": "PT",
    "palau": "PW",
    "paraguay": "PY",
    "qatar": "QA",
    "reunion": "RE",
    "romania": "RO",
    "serbia": "RS",
    "russia": "RU",
    "russian federation": "RU",
    "rwanda": "RW",
    "saudi arabia": "SA",
    "solomon islands": "SB",
    "seychelles": "SC",
    "sudan": "SD",
    "sweden": "SE",
    "singapore": "SG",
    "saint helena": "SH",
    "slovenia": "SI",
    "svalbard and jan mayen": "SJ",
    "slovakia": "SK",
    "sierra leone": "SL",
    "san marino": "SM",
    "senegal": "SN",
    "somalia": "SO",
    "suriname": "SR",
    "south sudan": "SS",
    "sao tome and principe": "ST",
    "el salvador": "SV",
    "sint maarten": "SX",
    "syria": "SY",
    "eswatini": "SZ",
    "swaziland": "SZ",
    "turks and caicos islands": "TC",
    "chad": "TD",
    "french southern territories": "TF",
    "togo": "TG",
    "thailand": "TH",
    "tajikistan": "TJ",
    "tokelau": "TK",
    "timor-leste": "TL",
    "east timor": "TL",
    "turkmenistan": "TM",
    "tunisia": "TN",
    "tonga": "TO",
    "turkey": "TR",
    "turkiye": "TR",
    "trinidad and tobago": "TT",
    "tuvalu": "TV",
    "taiwan": "TW",
    "tanzania": "TZ",
    "ukraine": "UA",
    "uganda": "UG",
    "united states minor outlying islands": "UM",
    "united states": "US",
    "united states of america": "US",
    "usa": "US",
    "u.s.a.": "US",
    "u.s.": "US",
    "america": "US",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "vatican city": "VA",
    "holy see": "VA",
    "saint vincent and the grenadines": "VC",
    "venezuela": "VE",
    "british virgin islands": "VG",
    "us virgin islands": "VI",
    "vietnam": "VN",
    "viet nam": "VN",
    "vanuatu": "VU",
    "wallis and futuna": "WF",
    "samoa": "WS",
    "kosovo": "XK",
    "yemen": "YE",
    "mayotte": "YT",
    "south africa": "ZA",
    "zambia": "ZM",
    "zimbabwe": "ZW",
    # Aliases that don't fit the alpha-sort above.
    "uk": "GB",
    "u.k.": "GB",
    "uae": "AE",
    "u.a.e.": "AE",
}

# Set of every valid alpha-2 code, for "already a code" checks.
CODES: frozenset[str] = frozenset(NAME_TO_CODE.values())


def resolve(value: str) -> str | None:
    """Return the ISO 3166-1 alpha-2 code for a country name/alias, else None.

    Normalises case, strips diacritics ("Türkiye" → TR, "Réunion" → RE),
    collapses internal whitespace, and ignores a leading "the" ("the
    netherlands" → NL). Already-valid 2-letter codes are returned upper-cased
    so callers can treat the result uniformly.
    """
    decomposed = unicodedata.normalize("NFKD", value)
    ascii_value = "".join(ch for ch in decomposed if not unicodedata.combining(ch))
    norm = re.sub(r"\s+", " ", ascii_value.strip().lower())
    if not norm:
        return None
    if re.fullmatch(r"[a-z]{2}", norm) and norm.upper() in CODES:
        return norm.upper()
    if norm.startswith("the "):
        norm = norm[4:]
    return NAME_TO_CODE.get(norm)


# US state/territory name → ISO 3166-2 region code (without the "US-" prefix).
#
# Shodan keys US states via the ``region:`` filter using this 2-letter code —
# NOT the full name ("region:Illinois" matches zero hosts; "region:IL" matches
# thousands). Empirically verified against Shodan's free count endpoint. Because
# region codes collide across countries (WA = Washington *and* Western
# Australia), a region rewrite must always be scoped with ``country:US``.
US_STATE_TO_CODE: dict[str, str] = {
    "alabama": "AL", "alaska": "AK", "arizona": "AZ", "arkansas": "AR",
    "california": "CA", "colorado": "CO", "connecticut": "CT", "delaware": "DE",
    "florida": "FL", "georgia": "GA", "hawaii": "HI", "idaho": "ID",
    "illinois": "IL", "indiana": "IN", "iowa": "IA", "kansas": "KS",
    "kentucky": "KY", "louisiana": "LA", "maine": "ME", "maryland": "MD",
    "massachusetts": "MA", "michigan": "MI", "minnesota": "MN", "mississippi": "MS",
    "missouri": "MO", "montana": "MT", "nebraska": "NE", "nevada": "NV",
    "new hampshire": "NH", "new jersey": "NJ", "new mexico": "NM", "new york": "NY",
    "north carolina": "NC", "north dakota": "ND", "ohio": "OH", "oklahoma": "OK",
    "oregon": "OR", "pennsylvania": "PA", "rhode island": "RI", "south carolina": "SC",
    "south dakota": "SD", "tennessee": "TN", "texas": "TX", "utah": "UT",
    "vermont": "VT", "virginia": "VA", "washington": "WA", "west virginia": "WV",
    "wisconsin": "WI", "wyoming": "WY",
    # Federal district + territories.
    "district of columbia": "DC", "washington dc": "DC", "washington d.c.": "DC",
    "puerto rico": "PR", "guam": "GU", "us virgin islands": "VI",
    "u.s. virgin islands": "VI", "american samoa": "AS",
    "northern mariana islands": "MP",
}


def resolve_us_state(value: str) -> str | None:
    """Return the 2-letter region code for a US state/territory *name*, else None.

    Name-only by design: a bare 2-letter code (already valid for ``region:``) is
    left for the caller to keep as-is. Normalises case, diacritics, internal
    whitespace, and a leading "the"."""
    decomposed = unicodedata.normalize("NFKD", value)
    ascii_value = "".join(ch for ch in decomposed if not unicodedata.combining(ch))
    norm = re.sub(r"\s+", " ", ascii_value.strip().lower())
    if norm.startswith("the "):
        norm = norm[4:]
    return US_STATE_TO_CODE.get(norm)
